stages:
  train_model:
    cmd: python src/models/train_model.py  data/raw/IMDB_Dataset.csv models/sentiment_analysis.joblib models/tfidf.joblib
    deps: 
      - src/models/train_model.py
      - data/raw/IMDB_Dataset.csv
    outs: 
      - models/sentiment_analysis.joblib
      - models/sentiment_analysis.joblib

  push_model:
    cmd: python src/models/push_model.py models/sentiment_analysis.joblib models/tfidf.joblib
    deps: 
      - src/models/push_model.py
